export default {
  RECIPESEARCH: {
    Redux: {
      RESET: 'RECIPESEARCH.REDUX.RESET',
      GET_RECIPE_SEARCH_FAILURE: 'RECIPESEARCH.REDUX.GET_RECIPE_SEARCH_FAILURE',
      GET_RECIPE_SEARCH_SUCCESS: 'RECIPESEARCH.REDUX.GET_RECIPE_SEARCH_SUCCESS',
      GET_RECIPE_SEARCH_LOADING: 'RECIPESEARCH.REDUX.GET_RECIPE_SEARCH_LOADING',
    },

    Saga: {
      GET_RECIPE_SEARCH_LIST: 'RECIPESEARCH.SAGA.GET_RECIPE_SEARCH_LIST',
    },
  },
};
