export default {
  POSTSEARCH: {
    Redux: {
      RESET: 'POSTSEARCH.REDUX.RESET',
      GET_POST_SEARCH_FAILURE: 'POSTSEARCH.REDUX.GET_POST_SEARCH_FAILURE',
      GET_POST_SEARCH_SUCCESS: 'POSTSEARCH.REDUX.GET_POST_SEARCH_SUCCESS',
      GET_POST_SEARCH_LOADING: 'POSTSEARCH.REDUX.GET_POST_SEARCH_LOADING',
    },

    Saga: {
      GET_POST_SEARCH_LIST: 'POSTSEARCH.SAGA.GET_POST_SEARCH_LIST',
    },
  },
};
