export default {
  YOUTUBE: {
    Redux: {
      RESET: 'YOUTUBE.REDUX.RESET',
      GET_YOUTUBE_FAILURE: 'YOUTUBE.REDUX.GET_YOUTUBE_FAILURE',
      GET_YOUTUBE_SUCCESS: 'YOUTUBE.REDUX.GET_YOUTUBE_SUCCESS',
      GET_YOUTUBE_LOADING: 'YOUTUBE.REDUX.GET_YOUTUBE_LOADING',
    },

    Saga: {
      GET_YOUTUBE_LIST: 'YOUTUBE.SAGA.GET_YOUTUBE_LIST',
    },
  },
};
