export default {
  FLASHSALE: {
    Redux: {
      RESET: 'FLASHSALE.REDUX.RESET',
      FLASHSALE_LOADING: 'FLASHSALE.REDUX.FLASHSALE_LOADING',
      GET_FLASHSALE_SUCCESS: 'FLASHSALE.REDUX.GET_FLASHSALE_SUCCESS',
      GET_FLASHSALE_PRODUCTS: 'FLASHSALE.REDUX.GET_FLASHSALE_PRODUCTS',
      GET_FLASHSALE_FAILURE: 'FLASHSALE.REDUX.GET_FLASHSALE_FAILURE',
    },
    Saga: {
      GET_FLASHSALE_DATA: 'FLASHSALE.SAGA.GET_FLASHSALE_DATA',
      GET_FLASHSALE_PRODUCTS: 'FLASHSALE.SAGA.GET_FLASHSALE_PRODUCTS',
      GET_FLASHSALE_DUMMY: 'FLASHSALE.SAGA.GET_FLASHSALE_DUMMY',
    },
  },
};
