export default {
  RECIPECATEGORIES: {
    Redux: {
      RESET: 'RECIPE.REDUX.RESET',
      GET_RECIPE_CATEGORIES_FAILURE:
        'RECIPE.REDUX.GET_RECIPE_CATEGORIES_FAILURE',
      GET_RECIPE_CATEGORIES_SUCCESS:
        'RECIPE.REDUX.GET_RECIPE_CATEGORIES_SUCCESS',
      GET_RECIPE_CATEGORIES_LOADING:
        'RECIPE.REDUX.GET_RECIPE_CATEGORIES_LOADING',
    },

    Saga: {
      GET_RECIPE_CATEGORIES_LIST: 'RECIPE.SAGA.GET_RECIPE_CATEGORIES_LIST',
    },
  },
};
