export default {
  SEARCH: {
    Redux: {
      RESET: 'SEARCH.REDUX.RESET',
      GET_SEARCH_FAILURE: 'SEARCH.REDUX.GET_SEARCH_FAILURE',
      GET_SEARCH_SUCCESS: 'SEARCH.REDUX.GET_SEARCH_SUCCESS',
      GET_SEARCH_LOADING: 'SEARCH.REDUX.GET_SEARCH_LOADING',
      SEARCH_ACTIVE: 'SEARCH.REDUX.SEARCH_ACTIVE',
    },

    Saga: {
      GET_SEARCH_LIST: 'SEARCH.SAGA.GET_SEARCH_LIST',
    },
  },
};
