export default {
  BRANDS: {
    Redux: {
      RESET: 'BRANDS.REDUX.RESET',
      GET_BRANDS_SUCCESS: 'BRANDS.REDUX.GET_BRANDS_SUCCESS',
      GET_BRANDS_FAILURE: 'BRANDS.REDUX.GET_BRANDS_FAILURE',
      SET_BRANDS_LOADING: 'BRANDS.REDUX.SET_BRANDS_LOADING',
      GET_FEATURED_BRANDS_SUCCESS: 'BRANDS.REDUX.GET_FEATURED_BRANDS_SUCCESS',
      SET_FEATURED_BRANDS_LOADING: 'BRANDS.REDUX.SET_FEATURED_BRANDS_LOADING',
      GET_BRAND_PRODUCTS_SUCCESS: 'BRANDS.REDUX.GET_BRAND_PRODUCTS_SUCCESS',
      GET_SEARCH_BRANDS_LIST: 'BRANDS.REDUX.GET_SEARCH_BRANDS_LIST',
      SET_SEARCH_BRANDS_LOADING: 'BRANDS.REDUX.SET_SEARCH_BRANDS_LOADING',
    },
    Saga: {
      GET_BRANDS: 'BRANDS.SAGA.GET_BRANDS',
      GET_FEATURED_BRANDS: 'BRANDS.SAGA.GET_FEATURED_BRANDS',
      GET_BRAND_PRODUCTS: 'BRANDS.SAGA.GET_BRAND_PRODUCTS',
      GET_SEARCH_BRANDS_LIST: 'BRANDS.SAGA.GET_SEARCH_BRANDS_LIST',
    },
  },
};
