export default {
  POST: {
    Redux: {
      SUCCESS: 'POST.REDUX.SUCCESS',
      FAILURE: 'POST.REDUX.FAILURE',
      RESET: 'POST.REDUX.RESET',

      // get post
      GET_POST_SUCCESS: 'POST.SAGA.GET_POST_SUCCESS',
      GET_POST_LOADING: 'POST.SAGA.GET_POST_LOADING',
      GET_POST_FAILURE: 'POST.SAGA.GET_POST_FAILURE',

      // get detail post
      GET_POST_DETAIL_SUCCESS: 'POST.SAGA.GET_POST_DETAIL_SUCCESS',
      GET_POST_DETAIL_LOADING: 'POST.SAGA.GET_POST_DETAIL_LOADING',
      GET_POST_DETAIL_FAILURE: 'POST.SAGA.GET_POST_DETAIL_FAILURE',

      // get list teman lama
      GET_POST_TEMAN_LAMA_SUCCESS: 'POST.SAGA.GET_POST_TEMAN_LAMA_SUCCESS',
      GET_POST_TEMAN_LAMA_LOADING: 'POST.SAGA.GET_POST_TEMAN_LAMA_LOADING',
      GET_POST_TEMAN_LAMA_FAILURE: 'POST.SAGA.GET_POST_TEMAN_LAMA_FAILURE',
    },

    Saga: {
      GET_POST_LIST: 'POST.SAGA.GET_POST_LIST',
      GET_POST_DETAIL: 'POST.SAGA.GET_POST_DETAIL',
      GET_POST_TEMAN_LAMA_LIST: 'POST.SAGA.GET_POST_TEMAN_LAMA_LIST',
    },
  },
};
