export default {
  ADDTOCART: {
    Redux: {
      RESET: 'ADDTOCART.REDUX.RESET',
      GET_ADDTOCART_FAILURE: 'ADDTOCART.REDUX.GET_ADDTOCART_FAILURE',
      GET_ADDTOCART_SUCCESS: 'ADDTOCART.REDUX.GET_ADDTOCART_SUCCESS',
      GET_ADDTOCART_LOADING: 'ADDTOCART.REDUX.GET_ADDTOCART_LOADING',
    },

    Saga: {
      GET_ADDTOCART_LIST: 'ADDTOCART.SAGA.GET_ADDTOCART_LIST',
      GET_ADDTOCART_RESET: 'ADDTOCART.SAGA.GET_ADDTOCART_RESET',
    },
  },
};
