export default {
  ME: {
    Redux: {
      RESET: 'ME.REDUX.RESET',
      UPDATE_FORM_VALUES: 'ME.REDUX.UPDATE_FORM_VALUES',
      UPDATE_FORM_SUBMITTING: 'ME.REDUX.UPDATE_FORM_SUBMITTING',

      // GET PROFILE
      GET_PROFILE_SUCCESS: 'ME.REDUX.GET_PROFILE_SUCCESS',
      GET_PROFILE_FAILURE: 'ME.REDUX.GET_PROFILE_FAILURE',
      GET_PROFILE_LOADING: 'ME.REDUX.GET_PROFILE_LOADING',

      // EDIT PROFILE
      EDIT_PROFILE_SUCCESS: 'ME.REDUX.EDIT_PROFILE_SUCCESS',
      EDIT_PROFILE_FAILURE: 'ME.REDUX.EDIT_PROFILE_FAILURE',
      EDIT_PROFILE_LOADING: 'ME.REDUX.EDIT_PROFILE_LOADING',

      // CHANGE PASSWORD
      CHANGE_PASSWORD_SUCCESS: 'ME.REDUX.CHANGE_PASSWORD_SUCCESS',
      CHANGE_PASSWORD_FAILURE: 'ME.REDUX.CHANGE_PASSWORD_FAILURE',
      CHANGE_PASSWORD_LOADING: 'ME.REDUX.CHANGE_PASSWORD_LOADING',

      // ADD ADDRESS
      ADD_ADDRESS_SUCCESS: 'ME.REDUX.ADD_ADDRESS_SUCCESS',
      ADD_ADDRESS_FAILURE: 'ME.REDUX.ADD_ADDRESS_FAILURE',
      ADD_ADDRESS_LOADING: 'ME.REDUX.ADD_ADDRESS_LOADING',

      // EDIT ADDRESS
      EDIT_ADDRESS_SUCCESS: 'ME.REDUX.EDIT_ADDRESS_SUCCESS',
      EDIT_ADDRESS_FAILURE: 'ME.REDUX.EDIT_ADDRESS_FAILURE',
      EDIT_ADDRESS_LOADING: 'ME.REDUX.EDIT_ADDRESS_LOADING',

      // SET MAIN ADDRESS
      SET_MAIN_ADDRESS_SUCCESS: 'ME.REDUX.SET_MAIN_ADDRESS_SUCCESS',
      SET_MAIN_ADDRESS_FAILURE: 'ME.REDUX.SET_MAIN_ADDRESS_FAILURE',
      SET_MAIN_ADDRESS_LOADING: 'ME.REDUX.SET_MAIN_ADDRESS_LOADING',

      // DELETE ADDRESS
      DELETE_ADDRESS_SUCCESS: 'ME.REDUX.DELETE_ADDRESS_SUCCESS',
      DELETE_ADDRESS_FAILURE: 'ME.REDUX.DELETE_ADDRESS_FAILURE',
      DELETE_ADDRESS_LOADING: 'ME.REDUX.DELETE_ADDRESS_LOADING',

      // GET WISHLIST
      GET_WISHLIST_SUCCESS: 'ME.REDUX.GET_WISHLIST_SUCCESS',
      GET_WISHLIST_FAILURE: 'ME.REDUX.GET_WISHLIST_FAILURE',
      GET_WISHLIST_LOADING: 'ME.REDUX.GET_WISHLIST_LOADING',
    },

    Saga: {
      GET_PROFILE: 'ME.SAGA.GET_PROFILE',
      EDIT_PROFILE: 'ME.SAGA.EDIT_PROFILE',
      CHANGE_PASSWORD: 'ME.SAGA.CHANGE_PASSWORD',
      ADD_ADDRESS: 'ME.SAGA.ADD_ADDRESS',
      EDIT_ADDRESS: 'ME.SAGA.EDIT_ADDRESS',
      SET_MAIN_ADDRESS: 'ME.SAGA.SET_MAIN_ADDRESS',
      DELETE_ADDRESS: 'ME.SAGA.DELETE_ADDRESS',
      GET_WISHLIST: 'ME.SAGA.GET_WISHLIST',
    },
  },
};
