export default {
  PRODUCT_BY_SLUG: {
    Redux: {
      RESET: 'PRODUCT_BY_SLUG.REDUX.RESET',
      GET_PRODUCT_BY_SLUG_FAILURE:
        'PRODUCT_BY_SLUG.REDUX.GET_PRODUCT_BY_SLUG_FAILURE',
      GET_PRODUCT_BY_SLUG_SUCCESS:
        'PRODUCT_BY_SLUG.REDUX.GET_PRODUCT_BY_SLUG_SUCCESS',
      GET_PRODUCT_BY_SLUG_LOADING:
        'PRODUCT_BY_SLUG.REDUX.GET_PRODUCT_BY_SLUG_LOADING',
      PRODUCT_BY_SLUG_ACTIVE: 'PRODUCT_BY_SLUG.REDUX.PRODUCT_BY_SLUG_ACTIVE',
      SET_PRODUCT_BY_SLUG_PRICE:
        'PRODUCT_BY_SLUG.REDUX.SET_PRODUCT_BY_SLUG_PRICE',
    },

    Saga: {
      GET_PRODUCT_BY_SLUG_LIST: 'PRODUCT_BY_SLUG.SAGA.GET_PRODUCT_BY_SLUG_LIST',
    },
  },
};
