export default {
  POSTBEAUTY: {
    Redux: {
      RESET: 'POST.REDUX.RESET',
      GET_BEAUTY_FAILURE: 'POST.REDUX.GET_BEAUTY_FAILURE',
      GET_BEAUTY_SUCCESS: 'POST.REDUX.GET_BEAUTY_SUCCESS',
      GET_BEAUTY_LOADING: 'POST.REDUX.GET_BEAUTY_LOADING',
    },

    Saga: {
      GET_BEAUTY_LIST: 'POST.SAGA.GET_BEAUTY_LIST',
    },
  },
};
