export default {
  PRODUCT_DIET: {
    Redux: {
      RESET: 'PRODUCT_DIET.REDUX.RESET',
      GET_PRODUCT_DIET_BY_LIFESTYLE_FAILURE:
        'PRODUCT_DIET.REDUX.GET_PRODUCT_DIET_BY_LIFESTYLE_FAILURE',
      GET_PRODUCT_DIET_BY_LIFESTYLE_SUCCESS:
        'PRODUCT_DIET.REDUX.GET_PRODUCT_DIET_BY_LIFESTYLE_SUCCESS',
      GET_PRODUCT_DIET_BY_LIFESTYLE_LOADING:
        'PRODUCT_DIET.REDUX.GET_PRODUCT_DIET_BY_LIFESTYLE_LOADING',
    },

    Saga: {
      GET_PRODUCT_DIET_BY_LIFESTYLE:
        'PRODUCT_DIET.SAGA.GET_PRODUCT_DIET_BY_LIFESTYLE',
    },
  },
};
