export default {
  RECIPE: {
    Redux: {
      RESET: 'RECIPE.REDUX.RESET',
      GET_RECIPE_FAILURE: 'RECIPE.REDUX.GET_RECIPE_FAILURE',
      GET_RECIPE_SUCCESS: 'RECIPE.REDUX.GET_RECIPE_SUCCESS',
      GET_RECIPE_LOADING: 'RECIPE.REDUX.GET_RECIPE_LOADING',
      GET_RECIPE_CATEGORY_FAILURE: 'RECIPE.REDUX.GET_RECIPE_CATEGORY_FAILURE',
      GET_RECIPE_CATEGORY_SUCCESS: 'RECIPE.REDUX.GET_RECIPE_CATEGORY_SUCCESS',
      GET_RECIPE_CATEGORY_LOADING: 'RECIPE.REDUX.GET_RECIPE_CATEGORY_LOADING',
      GET_LATEST_RECIPE_FAILURE: 'RECIPE.REDUX.GET_LATEST_RECIPE_FAILURE',
      GET_LATEST_RECIPE_SUCCESS: 'RECIPE.REDUX.GET_LATEST_RECIPE_SUCCESS',
      GET_LATEST_RECIPE_LOADING: 'RECIPE.REDUX.GET_LATEST_RECIPE_LOADING',
      GET_POPULAR_RECIPE_FAILURE: 'RECIPE.REDUX.GET_POPULAR_RECIPE_FAILURE',
      GET_POPULAR_RECIPE_SUCCESS: 'RECIPE.REDUX.GET_POPULAR_RECIPE_SUCCESS',
      GET_POPULAR_RECIPE_LOADING: 'RECIPE.REDUX.GET_POPULAR_RECIPE_LOADING',
    },

    Saga: {
      GET_RECIPE_LIST: 'RECIPE.SAGA.GET_RECIPE_LIST',
      GET_RECIPE_BAHAN_UTAMA_LIST: 'RECIPE.SAGA.GET_RECIPE_BAHAN_UTAMA_LIST',
      GET_RECIPE_DIETARY_LIST: 'RECIPE.SAGA.GET_RECIPE_DIETARY_LIST',
      GET_RECIPE_CARA_MEMASAK_LIST: 'RECIPE.SAGA.GET_RECIPE_CARA_MEMASAK_LIST',
      GET_RECIPE_JENIS_HIDANGAN_LIST:
        'RECIPE.SAGA.GET_RECIPE_JENIS_HIDANGAN_LIST',
      GET_RECIPE_OTHER: 'RECIPE.SAGA.GET_RECIPE_OTHER',
      GET_LATEST_RECIPE_LIST: 'RECIPE.SAGA.GET_LATEST_RECIPE_LIST',
      GET_POPULAR_RECIPE_LIST: 'RECIPE.SAGA.GET_POPULAR_RECIPE_LIST',
    },
  },
};
