export default {
  POSTRELATED: {
    Redux: {
      RESET: 'POSTRELATED.REDUX.RESET',
      GET_POST_RELATED_FAILURE: 'POSTRELATED.REDUX.GET_POST_RELATED_FAILURE',
      GET_POST_RELATED_SUCCESS: 'POSTRELATED.REDUX.GET_POST_RELATED_SUCCESS',
      GET_POST_RELATED_LOADING: 'POSTRELATED.REDUX.GET_POST_RELATED_LOADING',
    },

    Saga: {
      GET_POST_RELATED_LIST: 'POSTRELATED.SAGA.GET_POST_RELATED_LIST',
    },
  },
};
