export default {
  SIGNUP: {
    Redux: {
      RESET: 'SIGNUP.REDUX.RESET',
      REGISTER_CUSTOMER_SUCCESS: 'SIGNUP.REDUX.REGISTER_CUSTOMER_SUCCESS',
      REGISTER_CUSTOMER_FAILURE: 'SIGNUP.REDUX.REGISTER_CUSTOMER_FAILURE',
      REGISTER_CUSTOMER_LOADING: 'SIGNUP.REDUX.REGISTER_CUSTOMER_LOADING',
    },

    Saga: {
      REGISTER_CUSTOMER: 'SIGNUP.REGISTER_CUSTOMER',
    },
  },
};
