export default {
  TIKTOK: {
    Redux: {
      RESET: 'TIKTOK.REDUX.RESET',
      GET_TIKTOK_FAILURE: 'TIKTOK.REDUX.GET_TIKTOK_FAILURE',
      GET_TIKTOK_SUCCESS: 'TIKTOK.REDUX.GET_TIKTOK_SUCCESS',
      GET_TIKTOK_LOADING: 'TIKTOK.REDUX.GET_TIKTOK_LOADING',
    },

    Saga: {
      GET_TIKTOK_LIST: 'TIKTOK.SAGA.GET_TIKTOK_LIST',
    },
  },
};
