export default {
  RECIPERELATED: {
    Redux: {
      RESET: 'RECIPE.REDUX.RESET',
      GET_RECIPE_RELATED_FAILURE: 'RECIPE.REDUX.GET_RECIPE_RELATED_FAILURE',
      GET_RECIPE_RELATED_SUCCESS: 'RECIPE.REDUX.GET_RECIPE_RELATED_SUCCESS',
      GET_RECIPE_RELATED_LOADING: 'RECIPE.REDUX.GET_RECIPE_RELATED_LOADING',
    },

    Saga: {
      GET_RECIPE_RELATED_LIST: 'RECIPE.SAGA.GET_RECIPE_RELATED_LIST',
    },
  },
};
