export default {
  INSTAGRAM: {
    Redux: {
      RESET: 'INSTAGRAM.REDUX.RESET',
      GET_INSTAGRAM_FAILURE: 'INSTAGRAM.REDUX.GET_INSTAGRAM_FAILURE',
      GET_INSTAGRAM_SUCCESS: 'INSTAGRAM.REDUX.GET_INSTAGRAM_SUCCESS',
      GET_INSTAGRAM_LOADING: 'INSTAGRAM.REDUX.GET_INSTAGRAM_LOADING',
    },

    Saga: {
      GET_INSTAGRAM_LIST: 'INSTAGRAM.SAGA.GET_INSTAGRAM_LIST',
    },
  },
};
