export default {
  BANNERSHOP: {
    Redux: {
      RESET: 'BANNERSHOP.REDUX.RESET',
      GET_BANNER_UTAMA: 'BANNERSHOP.REDUX.GET_BANNER_UTAMA',
      GET_BANNER_PROMO_PILIHAN: 'BANNERSHOP.REDUX.GET_BANNER_PROMO_PILIHAN',
      GET_BANNERSHOP_FAILURE: 'BANNERSHOP.REDUX.GET_BANNERSHOP_FAILURE',
      GET_BACKGROUND_PROMO: 'BANNERSHOP.REDUX.GET_BACKGROUND_ROMO',
      GET_BANNER_NEWFEATURE: 'BANNERSHOP.REDUX.GET_BANNER_NEWFEATURE',
      GET_BANNER_GOODANDGIFT: 'BANNERSHOP.REDUX.GET_BANNER_GOODANDGIFT',
      GET_BANNER_PROMO_BRAND: 'BANNERSHOP.REDUX.GET_BANNER_PROMO_BRAND',
    },
    Saga: {
      GET_BANNER_SHOPPING: 'BANNERSHOP.SAGA.GET_BANNER_SHOPPING',
    },
  },
};
