export default {
  INFO: {
    Redux: {
      RESET: 'INFO.REDUX.RESET',
      GET_INFO_FAILURE: 'INFO.REDUX.GET_INFO_FAILURE',
      GET_INFO_SUCCESS: 'INFO.REDUX.GET_INFO_SUCCESS',
      GET_INFO_LOADING: 'INFO.REDUX.GET_INFO_LOADING',
      POST_FIREBASE_FAILURE: 'INFO.REDUX.POST_FIREBASE_FAILURE',
      POST_FIREBASE_SUCCESS: 'INFO.REDUX.POST_FIREBASE_SUCCESS',
      POST_FIREBASE_LOADING: 'INFO.REDUX.POST_FIREBASE_LOADING',
    },

    Saga: {
      GET_INFO_LIST: 'INFO.SAGA.GET_INFO_LIST',
      POST_FIREBASE_LIST: 'INFO.SAGA.POST_FIREBASE_LIST',
    },
  },
};
