export default {
  PRODUCT_BY_CATEGORY: {
    Redux: {
      RESET: 'PRODUCT_BY_CATEGORY.REDUX.RESET',
      GET_PRODUCT_BY_CATEGORY_FAILURE:
        'PRODUCT_BY_CATEGORY.REDUX.GET_PRODUCT_BY_CATEGORY_FAILURE',
      GET_PRODUCT_BY_CATEGORY_SUCCESS:
        'PRODUCT_BY_CATEGORY.REDUX.GET_PRODUCT_BY_CATEGORY_SUCCESS',
      GET_PRODUCT_BY_CATEGORY_LOADING:
        'PRODUCT_BY_CATEGORY.REDUX.GET_PRODUCT_BY_CATEGORY_LOADING',
      GET_MORE_PRODUCT_BY_CATEGORY_SUCCESS:
        'PRODUCT_BY_CATEGORY.REDUX.GET_MORE_PRODUCT_BY_CATEGORY_SUCCESS',
      GET_MORE_PRODUCT_BY_CATEGORY_LOADING:
        'PRODUCT_BY_CATEGORY.REDUX.GET_MORE_PRODUCT_BY_CATEGORY_LOADING',
      GET_LIST_PRODUCT_SLIDER:
        'PRODUCT_BY_CATEGORY.REDUX.GET_LIST_PRODUCT_SLIDER',
      GET_LIST_PRODUCT_CATEGORY_SLIDER:
        'PRODUCT_BY_CATEGORY.REDUX.GET_LIST_PRODUCT_CATEGORY_SLIDER',
      GET_LIST_PRODUCT_PREMIUM_SLIDER_FAILURE:
        'PRODUCT_BY_CATEGORY.REDUX.GET_LIST_PRODUCT_PREMIUM_SLIDER_FAILURE',
      GET_LIST_PRODUCT_PREMIUM_SLIDER_SUCCESS:
        'PRODUCT_BY_CATEGORY.REDUX.GET_LIST_PRODUCT_PREMIUM_SLIDER_SUCCESS',
      GET_LIST_PRODUCT_PREMIUM_SLIDER_LOADING:
        'PRODUCT_BY_CATEGORY.REDUX.GET_LIST_PRODUCT_PREMIUM_SLIDER_LOADING',
    },

    Saga: {
      GET_PRODUCT_BY_CATEGORY_LIST:
        'PRODUCT_BY_CATEGORY.SAGA.GET_PRODUCT_BY_CATEGORY_LIST',
      GET_PRODUCT_BY_SUB_CATEGORY_LIST:
        'PRODUCT_BY_CATEGORY.SAGA.GET_PRODUCT_BY_SUB_CATEGORY_LIST',
      GET_MORE_PRODUCT_BY_CATEGORY_LIST:
        'PRODUCT_BY_CATEGORY.SAGA.GET_MORE_PRODUCT_BY_CATEGORY_LIST',
      GET_LIST_PRODUCT_SLIDER:
        'PRODUCT_BY_CATEGORY.SAGA.GET_LIST_PRODUCT_SLIDER',
      GET_LIST_PRODUCT_PREMIUM_SLIDER:
        'PRODUCT_BY_CATEGORY.SAGA.GET_LIST_PRODUCT_PREMIUM_SLIDER',
      GET_LIST_PRODUCT_CATEGORY_SLIDER:
        'PRODUCT_BY_CATEGORY.SAGA.GET_LIST_PRODUCT_CATEGORY_SLIDER',
    },
  },
};
