export default {
  RECIPE: {
    Redux: {
      RESET: 'RECIPE.REDUX.RESET',
      GET_RECIPE_CATALOG_FAILURE: 'RECIPE.REDUX.GET_RECIPE_CATALOG_FAILURE',
      GET_RECIPE_CATALOG_SUCCESS: 'RECIPE.REDUX.GET_RECIPE_CATALOG_SUCCESS',
      GET_RECIPE_CATALOG_LOADING: 'RECIPE.REDUX.GET_RECIPE_CATALOG_LOADING',
    },

    Saga: {
      GET_RECIPE_CATALOG_LIST: 'RECIPE.SAGA.GET_RECIPE_CATALOG_LIST',
    },
  },
};
