export default {
  TRANSACTION: {
    Redux: {
      RESET: 'TRANSACTION.REDUX.RESET',
      SET_FILTERS: 'TRANSACTION.REDUX.SET_FILTERS',

      // GET TRANSACTION LIST
      GET_TRANSACTION_LIST_SUCCESS:
        'TRANSACTION.REDUX.GET_TRANSACTION_LIST_SUCCESS',
      GET_TRANSACTION_LIST_FAILURE:
        'TRANSACTION.REDUX.GET_TRANSACTION_LIST_FAILURE',
      GET_TRANSACTION_LIST_LOADING:
        'TRANSACTION.REDUX.GET_TRANSACTION_LIST_LOADING',

      // GET ORDER DETAIL
      GET_ORDER_DETAIL_SUCCESS: 'TRANSACTION.REDUX.GET_ORDER_DETAIL_SUCCESS',
      GET_ORDER_DETAIL_FAILURE: 'TRANSACTION.REDUX.GET_ORDER_DETAIL_FAILURE',
      GET_ORDER_DETAIL_LOADING: 'TRANSACTION.REDUX.GET_ORDER_DETAIL_LOADING',
    },

    Saga: {
      GET_TRANSACTION_LIST: 'TRANSACTION.SAGA.GET_TRANSACTION_LIST',
      GET_ORDER_DETAIL: 'TRANSACTION.SAGA.GET_ORDER_DETAIL',
    },
  },
};
