export default {
  CONFIRM_PAYMENT: {
    Redux: {
      RESET: 'CONFIRM_PAYMENT.REDUX.RESET',
      CONFIRM_PAYMENT_SUCCESS: 'CONFIRM_PAYMENT.REDUX.CONFIRM_PAYMENT_SUCCESS',
      CONFIRM_PAYMENT_FAILURE: 'CONFIRM_PAYMENT.REDUX.CONFIRM_PAYMENT_FAILURE',
      CONFIRM_PAYMENT_LOADING: 'CONFIRM_PAYMENT.REDUX.CONFIRM_PAYMENT_LOADING',
    },

    Saga: {
      SET_CONFIRM_PAYMENT: 'CONFIRM_PAYMENT.SET_CONFIRM_PAYMENT',
    },
  },
};
