export default {
  POSTPOPULAR: {
    Redux: {
      RESET: 'POST.REDUX.RESET',
      GET_POPULAR_FAILURE: 'POST.REDUX.GET_POPULAR_FAILURE',
      GET_POPULAR_SUCCESS: 'POST.REDUX.GET_POPULAR_SUCCESS',
      GET_POPULAR_LOADING: 'POST.REDUX.GET_POPULAR_LOADING',
    },

    Saga: {
      GET_POPULAR_LIST: 'POST.SAGA.GET_POPULAR_LIST',
    },
  },
};
