export default {
  RECIPETRICK: {
    Redux: {
      RESET: 'RECIPETRICK.REDUX.RESET',
      GET_RECIPE_TIPS_AND_TRICK_FAILURE:
        'RECIPETRICK.REDUX.GET_RECIPE_TIPS_AND_TRICK_FAILURE',
      GET_RECIPE_TIPS_AND_TRICK_SUCCESS:
        'RECIPETRICK.REDUX.GET_RECIPE_TIPS_AND_TRICK_SUCCESS',
      GET_RECIPE_TIPS_AND_TRICK_LOADING:
        'RECIPETRICK.REDUX.GET_RECIPE_TIPS_AND_TRICK_LOADING',
    },

    Saga: {
      GET_RECIPE_TIPS_AND_TRICK_LIST:
        'RECIPETRICK.SAGA.GET_RECIPE_TIPS_AND_TRICK_LIST',
    },
  },
};
