export default {
  CHECKOUT: {
    Redux: {
      RESET: 'CHECKOUT.REDUX.RESET',
      GET_CHECKOUT_SUCCESS: 'CHECKOUT.REDUX.GET_CHECKOUT_SUCCESS',
      GET_CHECKOUT_FAILURE: 'CHECKOUT.REDUX.GET_CHECKOUT_FAILURE',
      UPDATE_SALES_RULE: 'CHECKOUT.REDUX.UPDATE_SALES_RULE',
      GET_CHECKOUT_STATUS: 'CHECKOUT.REDUX.GET_CHECKOUT_STATUS',
      CHECKOUT_LOADING: 'CHECKOUT.REDUX.CHECKOUT_LOADING',
      SET_ORDER_DATA: 'CHECKOUT.REDUX.SET_ORDER_DATA',
      SET_LOADING_COUNTER: 'CHECKOUT.REDUX.SET_LOADING_COUNTER',
    },

    Saga: {
      GET_CHECKOUT: 'CHECKOUT.SAGA.GET_CHECKOUT',
      UPDATE_QTY: 'CHECKOUT.SAGA.UPDATE_QTY',
      UPDATE_SALES_RULE: 'CHECKOUT.SAGA.UPDATE_SALES_RULE',
      GET_CHECKOUT_STATUS: 'CHECKOUT.SAGA.GET_CHECKOUT_STATUS',
      DELETE_CART_ITEM: 'CHECKOUT.SAGA.DELETE_CART_ITEM',
    },
  },
};
