export default {
  ORDERDETAIL: {
    Redux: {
      RESET: 'ORDERDETAIL.REDUX.RESET',
      GET_ORDER_DETAIL_FAILURE: 'ORDERDETAIL.REDUX.GET_ORDER_DETAIL_FAILURE',
      GET_ORDER_DETAIL_SUCCESS: 'ORDERDETAIL.REDUX.GET_ORDER_DETAIL_SUCCESS',
      GET_ORDER_DETAIL_LOADING: 'ORDERDETAIL.REDUX.GET_ORDER_DETAIL_LOADING',
    },

    Saga: {
      GET_ORDER_DETAIL_LIST: 'ORDERDETAIL.SAGA.GET_ORDER_DETAIL_LIST',
    },
  },
};
