export default {
  FORGET_PASSWORD: {
    Redux: {
      RESET: 'FORGET_PASSWORD.REDUX.RESET',

      // SEND_EMAIL
      SEND_EMAIL_SUCCESS: 'FORGET_PASSWORD.REDUX.SEND_EMAIL_SUCCESS',
      SEND_EMAIL_FAILURE: 'FORGET_PASSWORD.REDUX.SEND_EMAIL_FAILURE',
      SEND_EMAIL_LOADING: 'FORGET_PASSWORD.REDUX.SEND_EMAIL_LOADING',

      // RESET_PASSWORD
      RESET_PASSWORD_SUCCESS: 'FORGET_PASSWORD.REDUX.RESET_PASSWORD_SUCCESS',
      RESET_PASSWORD_FAILURE: 'FORGET_PASSWORD.REDUX.RESET_PASSWORD_FAILURE',
      RESET_PASSWORD_LOADING: 'FORGET_PASSWORD.REDUX.RESET_PASSWORD_LOADING',
    },

    Saga: {
      SEND_EMAIL: 'FORGET_PASSWORD.SAGA.SEND_EMAIL',
      RESET_PASSWORD: 'FORGET_PASSWORD.SAGA.RESET_PASSWORD',
    },
  },
};
