export default {
  POSTCATEGORY: {
    Redux: {
      RESET: 'POST.REDUX.RESET',
      GET_POST_CATEGORY_FAILED: 'POST.REDUX.GET_POST_CATEGORY_FAILED',
      GET_POST_CATEGORY_SUCCESS: 'POST.REDUX.GET_POST_CATEGORY_SUCCESS',
      GET_POST_CATEGORY_LOADING: 'POST.REDUX.GET_POST_CATEGORY_LOADING',
    },

    Saga: {
      GET_POST_CATEGORY_LIST: 'POST.SAGA.GET_POST_CATEGORY_LIST',
    },
  },
};
