export default {
  CLAIM_PRODUCT: {
    Redux: {
      RESET: 'CLAIM_PRODUCT.REDUX.RESET',
      CLAIM_PRODUCT_SUCCESS: 'CLAIM_PRODUCT.REDUX.CLAIM_PRODUCT_SUCCESS',
      CLAIM_PRODUCT_FAILURE: 'CLAIM_PRODUCT.REDUX.CLAIM_PRODUCT_FAILURE',
      CLAIM_PRODUCT_LOADING: 'CLAIM_PRODUCT.REDUX.CLAIM_PRODUCT_LOADING',
    },

    Saga: {
      SET_CLAIM_PRODUCT: 'CLAIM_PRODUCT.SET_CLAIM_PRODUCT',
    },
  },
};
