export default {
  REFERAL: {
    Redux: {
      RESET: 'REFERAL.REDUX.RESET',
      GET_REFERAL_FAILURE: 'REFERAL.REDUX.GET_REFERAL_FAILURE',
      GET_REFERAL_SUCCESS: 'REFERAL.REDUX.GET_REFERAL_SUCCESS',
      GET_REFERAL_LOADING: 'REFERAL.REDUX.GET_REFERAL_LOADING',
    },

    Saga: {
      GET_REFERAL_CODE: 'REFERAL.SAGA.GET_REFERAL_CODE',
    },
  },
};
