export default {
  CLAIM_VOUCHER: {
    Redux: {
      RESET: 'CLAIM_VOUCHER.REDUX.RESET',
      CLAIM_VOUCHER_SUCCESS: 'CLAIM_VOUCHER.REDUX.CLAIM_VOUCHER_SUCCESS',
      CLAIM_VOUCHER_FAILURE: 'CLAIM_VOUCHER.REDUX.CLAIM_VOUCHER_FAILURE',
      CLAIM_VOUCHER_LOADING: 'CLAIM_VOUCHER.REDUX.CLAIM_VOUCHER_LOADING',
    },

    Saga: {
      SET_CLAIM_VOUCHER: 'CLAIM_VOUCHER.SET_CLAIM_VOUCHER',
    },
  },
};
