export default {
  LOGIN: {
    Redux: {
      RESET: 'LOGIN.REDUX.RESET',
      AUTHORIZE_SUCCESS: 'LOGIN.REDUX.AUTHORIZE_SUCCESS',
      AUTHORIZE_FAILURE: 'LOGIN.REDUX.AUTHORIZE_FAILURE',
      AUTHORIZE_LOADING: 'LOGIN.REDUX.AUTHORIZE_LOADING',
    },

    Saga: {
      AUTHORIZE: 'LOGIN.SAGA.AUTHORIZE',
    },
  },
};
