export default {
  PRODUCT_CATEGORIES: {
    Redux: {
      RESET: 'PRODUCT_CATEGORIES.REDUX.RESET',
      GET_PRODUCT_CATEGORIES_FAILURE:
        'PRODUCT_CATEGORIES.REDUX.GET_PRODUCT_CATEGORIES_FAILURE',
      GET_PRODUCT_CATEGORIES_SUCCESS:
        'PRODUCT_CATEGORIES.REDUX.GET_PRODUCT_CATEGORIES_SUCCESS',
      GET_PRODUCT_CATEGORIES_LOADING:
        'PRODUCT_CATEGORIES.REDUX.GET_PRODUCT_CATEGORIES_LOADING',
    },

    Saga: {
      GET_PRODUCT_CATEGORIES_LIST:
        'PRODUCT_CATEGORIES.SAGA.GET_PRODUCT_CATEGORIES_LIST',
    },
  },
};
